plugins:
  dwp_enabled:
    default: true
    type: bool
    client: true

  dwp_og_image:
    default: ""
    type: upload
  dwp_favicon:
    default: ""
    type: upload
  dwp_logo_dark:
    default: ""
    type: upload
  dwp_logo_light:
    default: ""
    type: upload
  dwp_footer_logo:
    default: ""
    type: upload
  dwp_hero_bg_image:
    default: ""
    type: upload
  dwp_hero_image:
    default: ""
    type: upload
  dwp_about_image:
    default: ""
    type: upload
  dwp_about_bg_image:
    default: ""
    type: upload
  dwp_faq_image:
    default: ""
    type: upload
  dwp_cta_image:
    default: ""
    type: upload
  dwp_ios_badge_image:
    default: ""
    type: upload
  dwp_android_badge_image:
    default: ""
    type: upload
  dwp_preloader_logo_dark:
    default: ""
    type: upload
  dwp_preloader_logo_light:
    default: ""
    type: upload
