plugins:
  domniq_web_enabled:
    default: true
    type: bool
    client: true

  domniq_web_og_image:
    default: ""
    type: upload
  domniq_web_favicon:
    default: ""
    type: upload
  domniq_web_use_site_logo:
    default: true
    type: bool

  domniq_web_telemetry_enabled:
    default: true
    type: bool

  domniq_web_logo_dark:
    default: ""
    type: upload
  domniq_web_logo_light:
    default: ""
    type: upload
  domniq_web_footer_logo:
    default: ""
    type: upload
  domniq_web_hero_bg_image:
    default: ""
    type: upload
  domniq_web_hero_image:
    default: ""
    type: upload
  domniq_web_about_image:
    default: ""
    type: upload
  domniq_web_about_bg_image:
    default: ""
    type: upload
  domniq_web_faq_image:
    default: ""
    type: upload
  domniq_web_cta_image:
    default: ""
    type: upload
  domniq_web_ios_badge_image:
    default: ""
    type: upload
  domniq_web_android_badge_image:
    default: ""
    type: upload
  domniq_web_preloader_logo_dark:
    default: ""
    type: upload
  domniq_web_preloader_logo_light:
    default: ""
    type: upload
