# frozen_string_literal: true

class SeedDwpDefaults < ActiveRecord::Migration[7.0]
  DEFAULTS = {
    # ── general ──
    ["general", "section_order"]    => "hero|stats|about|leaderboard|topics|faq|app_cta",
    ["general", "custom_css"]       => "",
    ["general", "meta_description"] => "",
    ["general", "json_ld_enabled"]  => "true",
    ["general", "icon_library"]     => "none",

    # ── design ──
    ["design", "accent_color"]                => "d4a24e",
    ["design", "accent_hover_color"]          => "c4922e",
    ["design", "dark_bg_color"]               => "06060f",
    ["design", "light_bg_color"]              => "F2F4F7",
    ["design", "orb_color"]                   => "",
    ["design", "orb_opacity"]                 => "50",
    ["design", "google_font_name"]            => "Outfit",
    ["design", "title_font_name"]             => "",
    ["design", "logo_height"]                 => "30",
    ["design", "logo_use_accent_color"]       => "false",
    ["design", "scroll_animation"]            => "fade_up",
    ["design", "staggered_reveal_enabled"]    => "true",
    ["design", "dynamic_background_enabled"]  => "true",
    ["design", "mouse_parallax_enabled"]      => "true",
    ["design", "scroll_progress_enabled"]     => "true",
    ["design", "preloader_enabled"]           => "false",
    ["design", "preloader_min_duration"]      => "800",
    ["design", "preloader_bar_color"]         => "",
    ["design", "preloader_bg_dark"]           => "",
    ["design", "preloader_bg_light"]          => "",
    ["design", "preloader_text_color_dark"]   => "",
    ["design", "preloader_text_color_light"]  => "",

    # ── hero ──
    ["hero", "hero_title"]                     => "Welcome to Our Creative HeadQuarters",
    ["hero", "hero_accent_enabled"]            => "true",
    ["hero", "hero_accent_word"]               => "0",
    ["hero", "hero_title_size"]                => "0",
    ["hero", "hero_title_letter_spacing"]      => "0",
    ["hero", "hero_subtitle"]                  => "Are you ready to start your creative journey?",
    ["hero", "hero_title_color_dark"]          => "",
    ["hero", "hero_title_color_light"]         => "",
    ["hero", "hero_subtitle_color_dark"]       => "",
    ["hero", "hero_subtitle_color_light"]      => "",
    ["hero", "hero_text_shadow"]               => "false",
    ["hero", "hero_card_enabled"]              => "true",
    ["hero", "hero_card_bg_dark"]              => "",
    ["hero", "hero_card_bg_light"]             => "",
    ["hero", "hero_card_opacity"]              => "0.85",
    ["hero", "hero_bg_effect"]                 => "none",
    ["hero", "hero_background_overlay"]        => "false",
    ["hero", "hero_overlay_color"]             => "000000",
    ["hero", "hero_overlay_opacity"]           => "60",
    ["hero", "hero_image_first"]               => "false",
    ["hero", "hero_image_weight"]              => "1",
    ["hero", "hero_image_max_height"]          => "60",
    ["hero", "hero_buttons_shadow"]            => "true",
    ["hero", "hero_primary_button_enabled"]    => "true",
    ["hero", "hero_primary_button_label"]      => "View Latest Topics",
    ["hero", "hero_primary_button_url"]        => "/latest",
    ["hero", "hero_primary_btn_color_dark"]    => "",
    ["hero", "hero_primary_btn_color_light"]   => "",
    ["hero", "hero_secondary_button_enabled"]  => "true",
    ["hero", "hero_secondary_button_label"]    => "Explore Our Spaces",
    ["hero", "hero_secondary_button_url"]      => "/login",
    ["hero", "hero_secondary_btn_color_dark"]  => "",
    ["hero", "hero_secondary_btn_color_light"] => "",
    ["hero", "hero_video_url"]                 => "",
    ["hero", "hero_video_button_color"]        => "",
    ["hero", "hero_video_button_position"]     => "center",
    ["hero", "hero_video_blur_on_hover"]       => "true",
    ["hero", "hero_content_alignment"]         => "left",
    ["hero", "hero_bg_dark"]                   => "",
    ["hero", "hero_bg_light"]                  => "",
    ["hero", "hero_min_height"]                => "0",
    ["hero", "hero_border_style"]              => "none",
    ["hero", "contributors_enabled"]           => "true",
    ["hero", "contributors_title_enabled"]     => "true",
    ["hero", "contributors_title"]             => "Top Creators",
    ["hero", "contributors_count_label_enabled"] => "true",
    ["hero", "contributors_count_label"]       => "Cheers",
    ["hero", "contributors_alignment"]         => "left",
    ["hero", "contributors_days"]              => "30",
    ["hero", "contributors_count"]             => "10",
    ["hero", "contributors_pill_max_width"]    => "340",
    ["hero", "contributors_pill_bg_dark"]      => "",
    ["hero", "contributors_pill_bg_light"]     => "",

    # ── stats ──
    ["stats", "stats_enabled"]       => "true",
    ["stats", "stat_labels_enabled"] => "true",
    ["stats", "stats_title_enabled"] => "true",
    ["stats", "stats_title"]         => "Premium Stats",
    ["stats", "stats_title_size"]    => "0",
    ["stats", "stats_min_height"]    => "0",
    ["stats", "stat_card_style"]     => "rectangle",
    ["stats", "stat_icon_color"]     => "d4a24e",
    ["stats", "stat_icon_bg_color"]  => "",
    ["stats", "stat_icon_shape"]     => "circle",
    ["stats", "stat_counter_color"]  => "",
    ["stats", "stat_members_label"]  => "Members",
    ["stats", "stat_topics_label"]   => "Topics",
    ["stats", "stat_posts_label"]    => "Posts",
    ["stats", "stat_likes_label"]    => "Likes",
    ["stats", "stat_chats_label"]    => "Chats",
    ["stats", "stat_round_numbers"]  => "false",
    ["stats", "stat_card_bg_dark"]   => "",
    ["stats", "stat_card_bg_light"]  => "",
    ["stats", "stats_bg_dark"]       => "",
    ["stats", "stats_bg_light"]      => "",
    ["stats", "stats_border_style"]  => "none",

    # ── about ──
    ["about", "about_enabled"]          => "true",
    ["about", "about_heading_enabled"]  => "true",
    ["about", "about_heading"]          => "About Community",
    ["about", "about_title_size"]       => "0",
    ["about", "about_title"]            => "Community Name",
    ["about", "about_role"]             => "",
    ["about", "about_body"]             => "",
    ["about", "about_card_color_dark"]  => "",
    ["about", "about_card_color_light"] => "",
    ["about", "about_bg_dark"]          => "",
    ["about", "about_bg_light"]         => "",
    ["about", "about_min_height"]       => "0",
    ["about", "about_border_style"]     => "none",

    # ── leaderboard ──
    ["leaderboard", "leaderboard_enabled"]       => "true",
    ["leaderboard", "leaderboard_title_enabled"] => "true",
    ["leaderboard", "leaderboard_title"]         => "Leaderboard",
    ["leaderboard", "leaderboard_title_size"]    => "0",
    ["leaderboard", "leaderboard_topics_label"]  => "Topics",
    ["leaderboard", "leaderboard_posts_label"]   => "Posts",
    ["leaderboard", "leaderboard_likes_label"]   => "Likes",
    ["leaderboard", "leaderboard_bio_max_length"] => "150",
    ["leaderboard", "leaderboard_accent_color"]  => "",
    ["leaderboard", "leaderboard_bio_color"]     => "",
    ["leaderboard", "leaderboard_card_bg_dark"]  => "",
    ["leaderboard", "leaderboard_card_bg_light"] => "",
    ["leaderboard", "leaderboard_bg_dark"]       => "",
    ["leaderboard", "leaderboard_bg_light"]      => "",
    ["leaderboard", "leaderboard_min_height"]    => "0",
    ["leaderboard", "leaderboard_border_style"]  => "none",

    # ── topics ──
    ["topics", "topics_enabled"]       => "true",
    ["topics", "topics_title_enabled"] => "true",
    ["topics", "topics_title"]         => "Trending Discussions",
    ["topics", "topics_title_size"]    => "0",
    ["topics", "topics_count"]         => "5",
    ["topics", "topics_min_height"]    => "0",
    ["topics", "topics_card_bg_dark"]  => "",
    ["topics", "topics_card_bg_light"] => "",
    ["topics", "topics_bg_dark"]       => "",
    ["topics", "topics_bg_light"]      => "",
    ["topics", "topics_border_style"]  => "none",

    # ── faq ──
    ["faq", "faq_enabled"]            => "true",
    ["faq", "faq_title_enabled"]      => "true",
    ["faq", "faq_title"]              => "Frequently Asked Questions",
    ["faq", "faq_title_size"]         => "0",
    ["faq", "faq_items"]              => '[{"q":"What is this community about?","a":"A creative community focused on sharing knowledge and building together."},{"q":"How do I join?","a":"Click the Get Started button to create your free account."},{"q":"Is it free?","a":"Yes! Basic membership is completely free."}]',
    ["faq", "faq_card_bg_dark"]       => "",
    ["faq", "faq_card_bg_light"]      => "",
    ["faq", "faq_mobile_max_height"]  => "0",
    ["faq", "faq_bg_dark"]            => "",
    ["faq", "faq_bg_light"]           => "",
    ["faq", "faq_min_height"]         => "0",

    # ── app_cta ──
    ["app_cta", "show_app_ctas"]                    => "true",
    ["app_cta", "app_cta_headline"]                 => "Get the best experience on our app",
    ["app_cta", "app_cta_headline_color_dark"]      => "",
    ["app_cta", "app_cta_headline_color_light"]     => "",
    ["app_cta", "app_cta_subtext"]                  => "Available free on iOS and Android",
    ["app_cta", "app_cta_subtext_color_dark"]       => "",
    ["app_cta", "app_cta_subtext_color_light"]      => "",
    ["app_cta", "app_cta_title_size"]               => "0",
    ["app_cta", "ios_app_url"]                      => "",
    ["app_cta", "android_app_url"]                  => "",
    ["app_cta", "app_badge_height"]                 => "45",
    ["app_cta", "app_badge_style"]                  => "rounded",
    ["app_cta", "app_cta_gradient_start_dark"]      => "1a1a2e",
    ["app_cta", "app_cta_gradient_start_light"]     => "e8edf3",
    ["app_cta", "app_cta_gradient_mid_dark"]        => "16213e",
    ["app_cta", "app_cta_gradient_mid_light"]       => "dce3ed",
    ["app_cta", "app_cta_gradient_end_dark"]        => "0f3460",
    ["app_cta", "app_cta_gradient_end_light"]       => "cdd8e8",
    ["app_cta", "app_cta_bg_dark"]                  => "",
    ["app_cta", "app_cta_bg_light"]                 => "",
    ["app_cta", "app_cta_min_height"]               => "0",
    ["app_cta", "app_cta_border_style"]             => "none",

    # ── navbar ──
    ["navbar", "navbar_text_color_dark"]    => "",
    ["navbar", "navbar_text_color_light"]   => "",
    ["navbar", "navbar_icon_color_dark"]    => "",
    ["navbar", "navbar_icon_color_light"]   => "",
    ["navbar", "navbar_signin_label"]       => "Sign In",
    ["navbar", "navbar_signin_enabled"]     => "true",
    ["navbar", "navbar_signin_color_dark"]  => "",
    ["navbar", "navbar_signin_color_light"] => "",
    ["navbar", "navbar_join_label"]         => "Get Started",
    ["navbar", "navbar_join_enabled"]       => "true",
    ["navbar", "navbar_join_color_dark"]    => "",
    ["navbar", "navbar_join_color_light"]   => "",
    ["navbar", "navbar_bg_color"]           => "",
    ["navbar", "navbar_border_style"]       => "none",
    ["navbar", "social_twitter_url"]        => "",
    ["navbar", "social_facebook_url"]       => "",
    ["navbar", "social_instagram_url"]      => "",
    ["navbar", "social_youtube_url"]        => "",
    ["navbar", "social_tiktok_url"]         => "",
    ["navbar", "social_github_url"]         => "",

    # ── footer ──
    ["footer", "footer_description"]      => "",
    ["footer", "footer_text"]             => "",
    ["footer", "footer_links"]            => '[{"label":"Brand","url":"/about"},{"label":"Links","url":"/links"},{"label":"Terms","url":"/tos"},{"label":"Privacy","url":"/privacy"}]',
    ["footer", "footer_bg_dark"]          => "",
    ["footer", "footer_bg_light"]         => "",
    ["footer", "footer_text_color_dark"]  => "",
    ["footer", "footer_text_color_light"] => "",
    ["footer", "footer_border_style"]     => "solid",
  }.freeze

  def up
    now = Time.current.iso8601
    DEFAULTS.each do |(config_type, config_key), default_value|
      execute <<~SQL
        INSERT INTO dwp_configs (config_type, config_key, config_value, position, enabled, created_at, updated_at)
        VALUES (#{quote(config_type)}, #{quote(config_key)}, #{quote(default_value.to_s)}, 0, TRUE, #{quote(now)}, #{quote(now)})
        ON CONFLICT (config_type, config_key) DO NOTHING
      SQL
    end
  end

  def down
    execute "DELETE FROM dwp_configs"
  end
end
